from tqdm.auto import tqdm
import re
from glob import glob
import numpy as np
import cv2
import scipy.ndimage
from numpy import int8
import os
from PIL import Image
Image.MAX_IMAGE_PIXELS = 1000000000

""" == GetSlideNames ==
Extracts a list of slide names.
By default, it searches for images with the prefix "Labels_" assuming prediction mask images.
File names are expected in the format:
Labels_slidename [d=,x=,y=,w=,h=].png
The slide name is extracted by splitting with a space character.
Since the image path is split using "\\" (Windows path separator), it may not work correctly with other directory separators.
"""
def GetSlideNames(
    path_list:list[str],
    file_dir:str=None,
    prefix:str="Labels_",
    extension:str="png"
):
    
    if path_list is None:
        path_list = sorted(glob(f"{file_dir}/*{extension}"))
        print(f"Got mask path from {file_dir}")
    else:
        path_list = sorted(path_list)
    
    print("Getting slide names")
    slidenames = []
    for path in path_list:
        path = os.path.basename(path)
        if prefix is None:
            slidenames.append(re.split("[ ]", path)[0])
        else:
            if path.startswith(prefix):
                path = path.replace(prefix, "")
                slidenames.append(re.split("[ ]", path)[0])
        slidenames = sorted(list(set(slidenames)))
    print(f"{len(slidenames)} slides were found")
    return slidenames


""" == MergeTiles ==
Merges tile images into a single whole-slide image for each slide.
- Provide either a list of image paths (path_list) or a directory containing the images.
- Coordinate information is read from file names, which must include [d=,x=,y=,w=,h=].
- The downsampling factor can be inferred from "d=" in the filename, or specified manually.
  (In QuPath, exporting at full resolution may omit "d="; in that case, it is treated as no downsampling.)
- If TrimOverlap=True, outer regions are cropped considering overlap, keeping only the center region.
  If TrimOverlap=False, overlap_px is ignored and set to 0.
  (If probability maps are averaged in overlap regions, trimming should not affect results.)
- If the save directory (save_dir) does not exist, it will be created.
- If makeColorMask=True, label index images are converted back to RGB color images.
  In that case, provide the path to the ColorMap .npy file generated by preparing_tools.MakeColorMap.
  Output is saved in a separate directory from the label index images.
  If you want to save in 8-bit color, set palette_mode=True (note: background conversion may occasionally fail).
- If saving in NumPy format is desired, set saved_format_npy=True; otherwise, images are saved as .png.
"""
def MergeTiles(pred_mask_dir:str="Pred_masks",
               imageSize:int=512,
               TrimOverlap:bool=False,
               overlap_px:int=256,
               downsample:int=None,
               save_dir:str="Pred_masks_merge",
               prefix:str="Labels",
               makeColorMask:bool=True,
               save_ColorMask_dir:str="Pred_ColorMasks",
               colormap_path:str="index.npy",
               pallete_mode:bool=False,
               path_list:list[str]=None,
               saved_format_npy:bool=False):
    
    if path_list is None:
        if saved_format_npy is True:
            path_list = sorted(glob(f"{pred_mask_dir}/{prefix}*npy"))
        else:
            path_list = sorted(glob(f"{pred_mask_dir}/{prefix}*png"))
        print(f"Got pred_mask path from {pred_mask_dir}")
    
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    if save_ColorMask_dir is not None:
        if not os.path.exists(save_ColorMask_dir):
            os.makedirs(save_ColorMask_dir)
            
    if TrimOverlap is False:
        overlap_px = 0
    
    overlap = int(overlap_px/2)
    
    slidenames = sorted(GetSlideNames(path_list=path_list, file_dir=None, extension="png"))
    for slide in tqdm(slidenames):
        print(f"<<<<<< Merging {slide} >>>>>>")
        
        paths = [s for s in path_list if slide in s]
        
        if downsample is None:
            path = os.path.basename(paths[0])
            if not "d=" in path:
                downsample = int(1)
            else:
                tile_info = [s for s in re.split("[ ]", path) if s.startswith('[')][-1]
                tile_info = re.split("[,.\\[\\]]", tile_info)
                downsample = int(re.split("[=]", tile_info[1])[1])
                
        if imageSize is None:
            path = os.path.basename(paths[0])
            tile_info = [s for s in re.split("[ ]", path) if s.startswith('[')][-1]
            tile_info = re.split("[,.\\[\\]]", tile_info)
            tile_size = int(re.split("[=]", tile_info[4])[1])
        else:
            tile_size = int(imageSize*downsample)

        x=[]; y=[]
        for path in paths:    
            x.append(int([p for p in re.split("[,\\[\\]]", os.path.basename(path)) if p.startswith("x")][0][2:]))
            y.append(int([p for p in re.split("[,\\[\\]]", os.path.basename(path)) if p.startswith("y")][0][2:]))
        x_max = max(x); y_max = max(y)

        merge = np.zeros((y_max + tile_size, x_max + tile_size), dtype = int8)

        for path in tqdm(paths):
            if saved_format_npy is True:
                img = np.load(path)
            else:
                img = Image.open(path)
                img = np.asarray(img)
                
            img = scipy.ndimage.zoom(img, downsample, order=0)

            crop_end = int(tile_size- overlap)
            img = img[overlap:crop_end, overlap:crop_end]

            x_start = int([p for p in re.split("[,\\[\\]]", os.path.basename(path)) if p.startswith("x")][0][2:]) + overlap
            y_start = int([p for p in re.split("[,\\[\\]]", os.path.basename(path)) if p.startswith("y")][0][2:]) + overlap
            x_end = x_start + tile_size-overlap_px
            y_end = y_start + tile_size-overlap_px
            merge[y_start:y_end, x_start:x_end] = img

        merge = scipy.ndimage.zoom(merge, 1/downsample, order=0)
        
        save_name = f"{slide} [d={downsample},x=0,y=0,w={x_max+(imageSize*downsample)},h={y_max+(imageSize*downsample)}].png"
        cv2.imwrite(f"{save_dir}/{save_name}", merge)
        
        if makeColorMask is True:
            print("Converting RGB mask")
            colormask = LabelToColorMask(label_img=merge,
                                         colormap_path=colormap_path,
                                         pallete_mode=pallete_mode)
            if pallete_mode is True:
                colormask.save(f"{save_ColorMask_dir}/{save_name}")
            else:
                colormask = cv2.cvtColor(colormask, cv2.COLOR_BGR2RGB)
                cv2.imwrite(f"{save_ColorMask_dir}/{save_name}", colormask)

        print(slide + " is saved!!")

""" == MergeTiles_from_ImageHolder ==
Merges tile images into a single whole-slide image for each slide.
This version uses the ImageHolder class defined in predict_tools.py.
Coordinate information and related metadata are stored as member variables in the ImageHolder instances and are used for reconstruction.
"""
def MergeTiles_from_ImageHolder(
    imgholder_list,
    imageSize:int=512,
    TrimOverlap:bool=False,
    overlap_px:int=256,
    downsample:int=None,
    save_dir:str="Pred_masks_merge",
    prefix:str="Labels",
    makeColorMask:bool=True,
    save_ColorMask_dir:str="Pred_ColorMasks",
    colormap_path:str="index.npy",
    pallete_mode:bool=False,
    path_list:list[str]=None,
):
    
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    if save_ColorMask_dir is not None:
        if not os.path.exists(save_ColorMask_dir):
            os.makedirs(save_ColorMask_dir)
    
    slidename = imgholder_list[0].slidename
    
    if TrimOverlap is False:
        overlap_px = 0
    overlap = int(overlap_px/2)
        
    if downsample is None:
        downsample = imgholder_list[0].tile_info["d"]
    tile_size = imgholder_list[0].tile_size

    x=[]; y=[]
    for imgholder in imgholder_list:    
        x.append(imgholder.tile_info["x"]); y.append(imgholder.tile_info["y"])
    x_max = max(x); y_max = max(y)

    merge = np.zeros((y_max + tile_size, x_max + tile_size), dtype = np.int8)

    print("--- Tiling masks ---")
    pbar = tqdm(total=len(imgholder_list))
    while imgholder_list:
        imgholder = imgholder_list.pop()
        
        img = imgholder.mask_final
        
        img = scipy.ndimage.zoom(img, downsample, order=0)

        crop_end = int(tile_size - overlap)
        img = img[overlap:crop_end, overlap:crop_end]

        x_start = imgholder.tile_info["x"] + overlap
        y_start = imgholder.tile_info["y"] + overlap
        x_end = x_start + tile_size - overlap_px
        y_end = y_start + tile_size - overlap_px
        merge[y_start:y_end, x_start:x_end] = img 
        
        pbar.update(1)
    pbar.close()

    merge = scipy.ndimage.zoom(merge, 1/downsample, order=0)

    save_name = f"{slidename} [d={downsample},x=0,y=0,w={x_max+(imageSize*downsample)},h={y_max+(imageSize*downsample)}].png"
    cv2.imwrite(f"{save_dir}/{save_name}", merge)

    if makeColorMask is True:
        print("--- Converting RGB mask ---")
        colormask = LabelToColorMask(label_img=merge,
                                     colormap_path=colormap_path,
                                     pallete_mode=pallete_mode)
        if pallete_mode is True:
            colormask.save(f"{save_ColorMask_dir}/{save_name}")
        else:
            colormask = cv2.cvtColor(colormask, cv2.COLOR_BGR2RGB)
            cv2.imwrite(f"{save_ColorMask_dir}/{save_name}", colormask)
        
        
""" == ReSplit ==
Re-tiles merged mask images (to reduce file size when handling them in QuPath).
- Coordinate information is read from the filename, so [d=,x=,y=,w=,h=] must be included in the filename.
- If downsample is not specified, it is read from the filename.
- You may provide either a list of merged image paths via path_list or a directory containing merged images via merged_mask_dir.
- tileSize can be set arbitrarily. The actual exported image size in pixels will be tileSize * downsample.
- If the save directory (save_dir) does not exist, it will be created.
"""

def ReSplit(merged_mask_dir:str="Pred_masks_merge",
            path_list:list[str]=None,
            tileSize:int=2000, 
            save_dir:str="Pred_masks_split", 
            downsample:int=None):
    
    if path_list is None:
        maskPaths = sorted(glob(f"{merged_mask_dir}/*png"))
    else:
        maskPaths = sorted(path_list)
    
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    
    for path in tqdm(maskPaths):
        basename = os.path.basename(path)
        slide_name = [s for s in re.split("[ ]", basename)][0]
        print(f"<<< Spliting -- {slide_name} -- >>>")
        
        if downsample is None:
            if not "d=" in basename:
                downsample = int(1)
            else:
                tile_info = [s for s in re.split("[ ]", basename) if s.startswith('[')][-1]
                tile_info = re.split("[,.\\[\\]]", tile_info)
                downsample = int(re.split("[=]", tile_info[1])[1])   

        mask = np.asarray(Image.open(path))

        height = mask.shape[0]; width = mask.shape[1]

        heightSplit = np.arange(0, height, tileSize)
        heightSplit = np.append(heightSplit , (heightSplit[-1] + height % tileSize))
        widthSplit = np.arange(0, width, tileSize)
        widthSplit = np.append(widthSplit , (widthSplit[-1] + width % tileSize))

        for i, w in enumerate(widthSplit[:-1]):
            for j, h in enumerate(heightSplit[:-1]):
                maskTile = mask[h:heightSplit[j+1], w:widthSplit[i+1]]
                tileHeight = maskTile.shape[0]
                tileWidth = maskTile.shape[1]

                cv2.imwrite(f"{save_dir}/{slide_name} [d={downsample},x={w},y={h},w={tileWidth*downsample},h={tileHeight*downsample}].png", maskTile)

        print(f"{slide_name} is saved!!")

        
"""
Converts label indices back to an RGB color image.
The colormap is assumed to be an .npy file generated by preparing_tools.MakeColorMap.
To re-import the image as QuPath annotations, an 8-bit color PNG is required.
If palette_mode=True, the image is converted to Pillow palette mode.
"""
def LabelToColorMask(label_img=None,
                     colormap:str=None,
                     label_img_path:str=None,
                     colormap_path:str=None,
                     pallete_mode:bool=True
                     ):
    
    if label_img is None:
        label_img = Image.open(label_img_path)
        label_img = np.asarray(label_img)
    
    rgb = np.zeros(shape=(label_img.shape[0],label_img.shape[1],3), dtype="uint8")
    
    if colormap is None:
        colormap = np.load(colormap_path)
    
    num_classes = len(colormap)
    for i in range(num_classes):
        rgb[label_img==i] = colormap[i]
    
    if pallete_mode is True:
        rgb = Image.fromarray(rgb)
        rgb = rgb.convert(mode="P", matrix=None, dither=0, colors=256, palette=0)
        # rgb.save(f"{save_dir}/{save_name}")

    return rgb

def LabelToColorMask_Batch(
    label_dir:str,
    colormap=None,
    colormap_path:str="index.npy",
    save_dir:str=None,
    pallete_mode:bool=False):
    
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    
    if colormap==None:
        colormap = np.load(colormap_path)
    num_classes = len(colormap)
    print("===== Color map =====")
    print(colormap); print("====================")
    
    imgPath = sorted(glob(f"{label_dir}/*png"))
    print("Converting index to color")
    for path in tqdm(imgPath):
        fname = os.path.basename(path)
        print(fname)
        label_img = Image.open(path)
        label_img = np.asarray(label_img)
    
        rgb = np.zeros(shape=(label_img.shape[0],label_img.shape[1],3), dtype="uint8")

        
        for i in tqdm(range(num_classes)):
            rgb[label_img==i] = colormap[i]
            
        if pallete_mode is True:
            rgb = Image.fromarray(rgb)
            rgb = rgb.convert(mode="P", matrix=None, dither=0, colors=256, palette=0)
            rgb.save(f"{save_dir}/{fname}")
        else:
            rgb = cv2.cvtColor(rgb, cv2.COLOR_BGR2RGB)
            cv2.imwrite(f"{save_dir}/{fname}", rgb)

